export const APPLY_COLOR_SUCCESS = "APPLY_COLOR_SUCCESS";
export const APPLY_COLOR_FAIL = "APPLY_COLOR_FAIL";

export const INCREASE_DECREASE_SCALE_SUCCESS = "INCREASE_DECREASE_SCALE_SUCCESS";
export const INCREASE_DECREASE_SCALE_FAIL = "INCREASE_DECREASE_SCALE_FAIL";

export const ENTER_AND_LEAVE_SCALE_SUCCESS = "ENTER_AND_LEAVE_SCALE_SUCCESS";
export const ENTER_AND_LEAVE_SCALE_FAIL = "ENTER_AND_LEAVE_SCALE_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";








